name: Auto

on:
  schedule:
    - cron: "0 * * * *"  # 北京时间上午06:30
  workflow_dispatch:

env:
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}  # API token stored in GitHub secrets
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}  # Base URL for the API
  DIFY_INPUTS: ${{ secrets.DIFY_INPUTS }}  # Any other inputs needed by the workflow

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Check out the code
      - uses: actions/setup-node@v2  # Set up Node.js environment
      - name: Install dependencies
        run: yarn  # Install dependencies with yarn
      - name: Debugging DIFY_INPUTS value
        run: echo "${{ secrets.DIFY_INPUTS }}"
      - name: Run Project and Make API request
        run: |
          # Make API request using curl with Authorization header
          curl -X POST "${{ env.DIFY_BASE_URL }}/workflows/run" \
          -H "Authorization: Bearer ${{ secrets.DIFY_TOKENS }}" \
          -H "Content-Type:application/json" \
          -d '{"inputs": "${{ secrets.DIFY_INPUTS }}"}'
          yarn workflowDify  # Run the project workflow after the API call
